// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testGiveaways(t *testing.T) {
	t.Parallel()

	query := Giveaways()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testGiveawaysDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Giveaway{}
	if err = randomize.Struct(seed, o, giveawayDBTypes, true, giveawayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Giveaway struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Giveaways().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGiveawaysQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Giveaway{}
	if err = randomize.Struct(seed, o, giveawayDBTypes, true, giveawayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Giveaway struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Giveaways().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Giveaways().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGiveawaysSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Giveaway{}
	if err = randomize.Struct(seed, o, giveawayDBTypes, true, giveawayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Giveaway struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := GiveawaySlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Giveaways().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGiveawaysExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Giveaway{}
	if err = randomize.Struct(seed, o, giveawayDBTypes, true, giveawayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Giveaway struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := GiveawayExists(ctx, tx, o.MessageID)
	if err != nil {
		t.Errorf("Unable to check if Giveaway exists: %s", err)
	}
	if !e {
		t.Errorf("Expected GiveawayExists to return true, but got false.")
	}
}

func testGiveawaysFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Giveaway{}
	if err = randomize.Struct(seed, o, giveawayDBTypes, true, giveawayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Giveaway struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	giveawayFound, err := FindGiveaway(ctx, tx, o.MessageID)
	if err != nil {
		t.Error(err)
	}

	if giveawayFound == nil {
		t.Error("want a record, got nil")
	}
}

func testGiveawaysBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Giveaway{}
	if err = randomize.Struct(seed, o, giveawayDBTypes, true, giveawayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Giveaway struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Giveaways().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testGiveawaysOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Giveaway{}
	if err = randomize.Struct(seed, o, giveawayDBTypes, true, giveawayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Giveaway struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Giveaways().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testGiveawaysAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	giveawayOne := &Giveaway{}
	giveawayTwo := &Giveaway{}
	if err = randomize.Struct(seed, giveawayOne, giveawayDBTypes, false, giveawayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Giveaway struct: %s", err)
	}
	if err = randomize.Struct(seed, giveawayTwo, giveawayDBTypes, false, giveawayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Giveaway struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = giveawayOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = giveawayTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Giveaways().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testGiveawaysCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	giveawayOne := &Giveaway{}
	giveawayTwo := &Giveaway{}
	if err = randomize.Struct(seed, giveawayOne, giveawayDBTypes, false, giveawayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Giveaway struct: %s", err)
	}
	if err = randomize.Struct(seed, giveawayTwo, giveawayDBTypes, false, giveawayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Giveaway struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = giveawayOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = giveawayTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Giveaways().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testGiveawaysInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Giveaway{}
	if err = randomize.Struct(seed, o, giveawayDBTypes, true, giveawayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Giveaway struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Giveaways().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testGiveawaysInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Giveaway{}
	if err = randomize.Struct(seed, o, giveawayDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Giveaway struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(giveawayColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Giveaways().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testGiveawaysReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Giveaway{}
	if err = randomize.Struct(seed, o, giveawayDBTypes, true, giveawayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Giveaway struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testGiveawaysReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Giveaway{}
	if err = randomize.Struct(seed, o, giveawayDBTypes, true, giveawayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Giveaway struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := GiveawaySlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testGiveawaysSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Giveaway{}
	if err = randomize.Struct(seed, o, giveawayDBTypes, true, giveawayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Giveaway struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Giveaways().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	giveawayDBTypes = map[string]string{`MessageID`: `bigint`, `GuildID`: `bigint`, `ChannelID`: `bigint`, `Author`: `bigint`, `Description`: `text`, `NumWinners`: `integer`, `ReactEmojiID`: `bigint`, `ReactEmojiUnicode`: `text`, `CreatedAt`: `timestamp with time zone`, `EndsAt`: `timestamp with time zone`, `EndedAt`: `timestamp with time zone`, `Winners`: `ARRAYbigint`, `Color`: `integer`}
	_               = bytes.MinRead
)

func testGiveawaysUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(giveawayPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(giveawayColumns) == len(giveawayPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Giveaway{}
	if err = randomize.Struct(seed, o, giveawayDBTypes, true, giveawayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Giveaway struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Giveaways().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, giveawayDBTypes, true, giveawayPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Giveaway struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testGiveawaysSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(giveawayColumns) == len(giveawayPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Giveaway{}
	if err = randomize.Struct(seed, o, giveawayDBTypes, true, giveawayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Giveaway struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Giveaways().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, giveawayDBTypes, true, giveawayPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Giveaway struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(giveawayColumns, giveawayPrimaryKeyColumns) {
		fields = giveawayColumns
	} else {
		fields = strmangle.SetComplement(
			giveawayColumns,
			giveawayPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := GiveawaySlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testGiveawaysUpsert(t *testing.T) {
	t.Parallel()

	if len(giveawayColumns) == len(giveawayPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Giveaway{}
	if err = randomize.Struct(seed, &o, giveawayDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Giveaway struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Giveaway: %s", err)
	}

	count, err := Giveaways().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, giveawayDBTypes, false, giveawayPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Giveaway struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Giveaway: %s", err)
	}

	count, err = Giveaways().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
